export default function useCharacterData() {
  return {
    limited: [
      { name: 'Albedo' },
      { name: 'Alhaitham' },
      { name: 'Arlecchino' },
      { name: 'Ayaka' },
      { name: 'Ayato' },
      { name: 'Baizhu' },
      { name: 'Childe' },
      { name: 'Chiori' },
      { name: 'Clorinde' },
      { name: 'Cyno' },
      { name: 'Emilie' },
      { name: 'Eula' },
      { name: 'Furina' },
      { name: 'Ganyu' },
      { name: 'Hu Tao' },
      { name: 'Itto' },
      { name: 'Kazuha' },
      { name: 'Klee' },
      { name: 'Kokomi' },
      { name: 'Lyney' },
      { name: 'Mualani' },
      { name: 'Nahida' },
      { name: 'Navia' },
      { name: 'Neuvillette' },
      { name: 'Nilou' },
      { name: 'Raiden Shogun' },
      { name: 'Shenhe' },
      { name: 'Sigewinne' },
      { name: 'Venti' },
      { name: 'Wanderer' },
      { name: 'Wriothesley' },
      { name: 'Xianyun' },
      { name: 'Xiao' },
      { name: 'Yae Miko' },
      { name: 'Yelan' },
      { name: 'Yoimiya' },
      { name: 'Zhongli' },
    ] as Character[],
    standard: [
      { name: 'Dehya' },
      { name: 'Diluc' },
      { name: 'Jean' },
      { name: 'Keqing' },
      { name: 'Mona' },
      { name: 'Qiqi' },
      { name: 'Tighnari' },
    ] as Character[],
  };
}
