export default function useWeaponData() {
  return {
    limited: [
      { name: 'A Thousand Floating Dreams', owner: 'Nahida' },
      { name: 'Absolution', owner: 'Clorinde' },
      { name: 'Aqua Simulacra', owner: 'Yelan' },
      { name: 'Beacon of the Reed Sea', owner: 'Dehya' },
      { name: 'Calamity Queller', owner: 'Shenhe' },
      { name: 'Cashflow Supervision', owner: 'Wriothesley' },
      { name: "Crane's Echoing Call", owner: 'Xianyun' },
      { name: "Crimson Moon's Semblance", owner: 'Arlecchino' },
      { name: 'Elegy for the End', owner: 'Venti' },
      { name: 'Engulfing Lightning', owner: 'Raiden Shogun' },
      { name: 'Everlasting Moonglow', owner: 'Kokomi' },
      { name: 'Freedom-Sworn', owner: 'Kazuha' },
      { name: 'Haran Geppaku Futsu', owner: 'Ayato' },
      { name: "Hunter's Path", owner: 'Tighnari' },
      { name: "Jadefall's Splendor", owner: 'Baizhu' },
      { name: "Kagura's Verity", owner: 'Yae Miko' },
      { name: 'Key of Khaj-Nisut', owner: 'Nilou' },
      { name: 'Light of Foliar Incision', owner: 'Alhaitham' },
      { name: 'Lumidouce Elegy', owner: 'Emilie' },
      { name: 'Memory of Dust' },
      { name: 'Mistsplitter Reforged', owner: 'Ayaka' },
      { name: 'Polar Star', owner: 'Childe' },
      { name: 'Primordial Jade Cutter' },
      { name: 'Redhorn Stonethresher', owner: 'Itto' },
      { name: 'Silvershower Heartstrings', owner: 'Sigewinne' },
      { name: 'Song of Broken Pines', owner: 'Eula' },
      { name: 'Splendor of Tranquil Waters', owner: 'Furina' },
      { name: 'Staff of Homa', owner: 'Hu Tao' },
      { name: 'Staff of the Scarlet Sands', owner: 'Cyno' },
      { name: 'Summit Shaper' },
      { name: "Surf's Up", owner: 'Mualani' },
      { name: 'The First Great Magic', owner: 'Lyney' },
      { name: 'The Unforged' },
      { name: 'Thundering Pulse', owner: 'Yoimiya' },
      { name: 'Tome of the Eternal Flow', owner: 'Neuvillette' },
      { name: "Tulaytullah's Remembrance", owner: 'Wanderer' },
      { name: 'Uraku Misugiri', owner: 'Chiori' },
      { name: 'Verdict', owner: 'Navia' },
      { name: 'Vortex Vanquisher', owner: 'Zhongli' },
    ] as Weapon[],
    standard: [
      { name: "Amos' Bow", owner: 'Ganyu' },
      { name: 'Aquila Favonia', owner: 'Jean' },
      { name: 'Lost Prayer to the Sacred Winds' },
      { name: 'Primordial Jade Winged-Spear', owner: 'Xiao' },
      { name: 'Skyward Atlas' },
      { name: 'Skyward Blade' },
      { name: 'Skyward Harp' },
      { name: 'Skyward Pride' },
      { name: 'Skyward Spine' },
      { name: "Wolf's Gravestone", owner: 'Diluc' },
    ] as Weapon[],
  };
}
